# Generated by Django 3.2.8 on 2022-01-14 10:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0004_alter_post_content'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='description',
            field=models.TextField(default='gggggggg'),
            preserve_default=False,
        ),
    ]
