# Generated by Django 3.2.8 on 2022-01-14 19:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0005_post_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='field',
            field=models.IntegerField(choices=[(0, 'Frontend Design'), (1, 'Python Programmes'), (2, 'Django Development'), (3, 'Article')], default=0),
        ),
        migrations.AddField(
            model_name='post',
            name='location',
            field=models.TextField(default='FFF'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='post',
            name='tags',
            field=models.TextField(default=1),
            preserve_default=False,
        ),
    ]
